export const CHALLENGE_ENV_CHALLENGE_ID = "TCH_CHALLENGE_ID"
export const CHALLENGE_ENV_DIR = "TCH_CHALLENGE_DIR"
export const CHALLENGE_ENV_API_BASE_URL = "TCH_CHALLENGE_API_BASE_URL"
export const CHALLENGE_ENV_AGENT_TOKEN = "TCH_CHALLENGE_AGENT_TOKEN"
