// generated by scripts/generate-builtin-assets.ts
import prompt_0 from "./prompts/builtin/CHALLENGE_PLANNER.md" with { type: "file" }
import prompt_1 from "./prompts/builtin/KALI_PROVISIONER.md" with { type: "file" }
import prompt_2 from "./prompts/builtin/OBJECTIVE_VERIFIER.md" with { type: "file" }
import prompt_3 from "./prompts/builtin/VULN_RESEARCHER.md" with { type: "file" }
import prompt_4 from "./prompts/builtin/kimi-security.md" with { type: "file" }
import skill_0 from "./skills/builtin/ffuf-skill/SKILL.md" with { type: "file" }
import skill_1 from "./skills/builtin/ffuf-skill/references/ffuf-web-params.md" with { type: "file" }
import skill_2 from "./skills/builtin/fuzz-dicts-skills/README.md" with { type: "file" }
import skill_3 from "./skills/builtin/fuzz-dicts-skills/SKILL.md" with { type: "file" }
import skill_4 from "./skills/builtin/fuzz-dicts-skills/XXEDicts/README.MD" with { type: "file" }
import skill_5 from "./skills/builtin/fuzz-dicts-skills/apiDict/api.txt" with { type: "file" }
import skill_6 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf-wscan/README.md" with { type: "file" }
import skill_7 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf-wscan/dict/default.txt" with { type: "file" }
import skill_8 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf-wscan/dict/ext.txt" with { type: "file" }
import skill_9 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf.txt" with { type: "file" }
import skill_10 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/Filenames_or_Directories_All.txt" with { type: "file" }
import skill_11 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/admin变种.txt" with { type: "file" }
import skill_12 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/asp/top30000.txt" with { type: "file" }
import skill_13 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/dicc.txt" with { type: "file" }
import skill_14 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/en_dirctories_all.txt" with { type: "file" }
import skill_15 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/fileName10000.txt" with { type: "file" }
import skill_16 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/jsp/top100.txt" with { type: "file" }
import skill_17 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/php/phpFileName.txt" with { type: "file" }
import skill_18 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/php/top3000.txt" with { type: "file" }
import skill_19 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/top7000.txt" with { type: "file" }
import skill_20 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vulns.txt" with { type: "file" }
import skill_21 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/LDAP.txt" with { type: "file" }
import skill_22 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/Traversal.txt" with { type: "file" }
import skill_23 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/XML.txt" with { type: "file" }
import skill_24 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/XXEExploit.txt" with { type: "file" }
import skill_25 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/all.txt" with { type: "file" }
import skill_26 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/apache.txt" with { type: "file" }
import skill_27 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/cgis.txt" with { type: "file" }
import skill_28 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/coldfusion.txt" with { type: "file" }
import skill_29 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/domino.txt" with { type: "file" }
import skill_30 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/fatwire.txt" with { type: "file" }
import skill_31 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/fatwire_pagenames.txt" with { type: "file" }
import skill_32 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/frontpage.txt" with { type: "file" }
import skill_33 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/iis.txt" with { type: "file" }
import skill_34 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/iplanet.txt" with { type: "file" }
import skill_35 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/jrun.txt" with { type: "file" }
import skill_36 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/netware.txt" with { type: "file" }
import skill_37 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/oracle9i.txt" with { type: "file" }
import skill_38 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/sharepoint.txt" with { type: "file" }
import skill_39 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/sunas.txt" with { type: "file" }
import skill_40 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/tests.txt" with { type: "file" }
import skill_41 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/tomcat.txt" with { type: "file" }
import skill_42 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/vignette.txt" with { type: "file" }
import skill_43 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/weblogic.txt" with { type: "file" }
import skill_44 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/websphere.txt" with { type: "file" }
import skill_45 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/README.md" with { type: "file" }
import skill_46 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/burpXssPayload.txt" with { type: "file" }
import skill_47 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/easyXssPayload.txt" with { type: "file" }
import skill_48 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/markdown-xss-payload.txt" with { type: "file" }
import skill_49 from "./skills/builtin/fuzz-dicts-skills/evals/evals.json" with { type: "file" }
import skill_50 from "./skills/builtin/fuzz-dicts-skills/images/README.MD" with { type: "file" }
import skill_51 from "./skills/builtin/fuzz-dicts-skills/js/jsFileDict.txt" with { type: "file" }
import skill_52 from "./skills/builtin/fuzz-dicts-skills/lotDict/acount.txt" with { type: "file" }
import skill_53 from "./skills/builtin/fuzz-dicts-skills/lotDict/password.txt" with { type: "file" }
import skill_54 from "./skills/builtin/fuzz-dicts-skills/paramDict/AllParam.txt" with { type: "file" }
import skill_55 from "./skills/builtin/fuzz-dicts-skills/paramDict/Arjun/CHANGELOG.md" with { type: "file" }
import skill_56 from "./skills/builtin/fuzz-dicts-skills/paramDict/Arjun/README.md" with { type: "file" }
import skill_57 from "./skills/builtin/fuzz-dicts-skills/paramDict/Arjun/db/params.txt" with { type: "file" }
import skill_58 from "./skills/builtin/fuzz-dicts-skills/paramDict/burp.txt" with { type: "file" }
import skill_59 from "./skills/builtin/fuzz-dicts-skills/paramDict/dir.txt" with { type: "file" }
import skill_60 from "./skills/builtin/fuzz-dicts-skills/paramDict/js.txt" with { type: "file" }
import skill_61 from "./skills/builtin/fuzz-dicts-skills/paramDict/parameter.txt" with { type: "file" }
import skill_62 from "./skills/builtin/fuzz-dicts-skills/paramDict/php.txt" with { type: "file" }
import skill_63 from "./skills/builtin/fuzz-dicts-skills/paramDict/vars.txt" with { type: "file" }
import skill_64 from "./skills/builtin/fuzz-dicts-skills/passwordDict/Middleware/axis.txt" with { type: "file" }
import skill_65 from "./skills/builtin/fuzz-dicts-skills/passwordDict/Middleware/tomcat-pass.txt" with { type: "file" }
import skill_66 from "./skills/builtin/fuzz-dicts-skills/passwordDict/Middleware/tomcat-user.txt" with { type: "file" }
import skill_67 from "./skills/builtin/fuzz-dicts-skills/passwordDict/Middleware/weblogic.txt" with { type: "file" }
import skill_68 from "./skills/builtin/fuzz-dicts-skills/passwordDict/Middleware/zabbix.txt" with { type: "file" }
import skill_69 from "./skills/builtin/fuzz-dicts-skills/passwordDict/README.MD" with { type: "file" }
import skill_70 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/README.md" with { type: "file" }
import skill_71 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/四个条件至少满足三个的6位数密码107965条.txt" with { type: "file" }
import skill_72 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/四个条件至少满足三个的8位数密码91286条.txt" with { type: "file" }
import skill_73 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/数字和字母同时存在的6位数密码76905条.txt" with { type: "file" }
import skill_74 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/数字和字母同时存在的8位数密码60850条.txt" with { type: "file" }
import skill_75 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/符合四个条件的6位数密码1633条.txt" with { type: "file" }
import skill_76 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/符合四个条件的8位数密码1420条.txt" with { type: "file" }
import skill_77 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字不能有三个相同的字符和特殊符号的6位数密码76905条.txt" with { type: "file" }
import skill_78 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字不能有三个相同的字符和特殊符号的8位数密码60850条.txt" with { type: "file" }
import skill_79 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字的6位数密码75945条.txt" with { type: "file" }
import skill_80 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字的8位数密码59995条.txt" with { type: "file" }
import skill_81 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个字母一个数字一个特殊符号的6位数密码27566条.txt" with { type: "file" }
import skill_82 from "./skills/builtin/fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个字母一个数字一个特殊符号的8位数密码26860条.txt" with { type: "file" }
import skill_83 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/ftp/init.txt" with { type: "file" }
import skill_84 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/ftp弱口令/ftp-pass.txt" with { type: "file" }
import skill_85 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/ftp弱口令/ftp-user.txt" with { type: "file" }
import skill_86 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/mstsc远程弱口令/3389.txt" with { type: "file" }
import skill_87 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/mysql弱口令/mysql-pass.txt" with { type: "file" }
import skill_88 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/mysql弱口令/mysql-user.txt" with { type: "file" }
import skill_89 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/ssh弱口令/ssh-pass.txt" with { type: "file" }
import skill_90 from "./skills/builtin/fuzz-dicts-skills/passwordDict/ServiceWeakPass/ssh弱口令/ssh-user.txt" with { type: "file" }
import skill_91 from "./skills/builtin/fuzz-dicts-skills/passwordDict/birth.txt" with { type: "file" }
import skill_92 from "./skills/builtin/fuzz-dicts-skills/passwordDict/top1000.txt" with { type: "file" }
import skill_93 from "./skills/builtin/fuzz-dicts-skills/passwordDict/top19576.txt" with { type: "file" }
import skill_94 from "./skills/builtin/fuzz-dicts-skills/passwordDict/top3000.txt" with { type: "file" }
import skill_95 from "./skills/builtin/fuzz-dicts-skills/passwordDict/top500.txt" with { type: "file" }
import skill_96 from "./skills/builtin/fuzz-dicts-skills/passwordDict/top6000.txt" with { type: "file" }
import skill_97 from "./skills/builtin/fuzz-dicts-skills/passwordDict/webshell-pass.txt" with { type: "file" }
import skill_98 from "./skills/builtin/fuzz-dicts-skills/passwordDict/wifi_top2000_passwd.txt" with { type: "file" }
import skill_99 from "./skills/builtin/fuzz-dicts-skills/passwordDict/某集团下发的弱口令字典.txt" with { type: "file" }
import skill_100 from "./skills/builtin/fuzz-dicts-skills/passwordDict/路由器默认密码.txt" with { type: "file" }
import skill_101 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/GhostScript-Rce.txt" with { type: "file" }
import skill_102 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Imagemagick-rce.txt" with { type: "file" }
import skill_103 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/RCE-filter-and-WAF-Bypass.txt" with { type: "file" }
import skill_104 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/README.md" with { type: "file" }
import skill_105 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Top-46-RCE-Parameters.txt" with { type: "file" }
import skill_106 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Unix-Commond-Inject-Payload-List.txt" with { type: "file" }
import skill_107 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Windows-Commond-Inject-Payload-List.txt" with { type: "file" }
import skill_108 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/rce-when-all-dangerous-characters-are-escaped.txt" with { type: "file" }
import skill_109 from "./skills/builtin/fuzz-dicts-skills/references/navigation.md" with { type: "file" }
import skill_110 from "./skills/builtin/fuzz-dicts-skills/references/tool-playbooks.md" with { type: "file" }
import skill_111 from "./skills/builtin/fuzz-dicts-skills/routerDicts/README.md" with { type: "file" }
import skill_112 from "./skills/builtin/fuzz-dicts-skills/routerDicts/pass.txt" with { type: "file" }
import skill_113 from "./skills/builtin/fuzz-dicts-skills/spring/spring-configuration-metadata.txt" with { type: "file" }
import skill_114 from "./skills/builtin/fuzz-dicts-skills/sqlDict/sql.txt" with { type: "file" }
import skill_115 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/aix_etc.txt" with { type: "file" }
import skill_116 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/centsOS_etc.txt" with { type: "file" }
import skill_117 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/config.txt" with { type: "file" }
import skill_118 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/lfi-scanner.txt" with { type: "file" }
import skill_119 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/linux常见路径.txt" with { type: "file" }
import skill_120 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/log.txt" with { type: "file" }
import skill_121 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/proc.txt" with { type: "file" }
import skill_122 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/ssrf.txt" with { type: "file" }
import skill_123 from "./skills/builtin/fuzz-dicts-skills/subdomainDicts/dic1.txt" with { type: "file" }
import skill_124 from "./skills/builtin/fuzz-dicts-skills/subdomainDicts/main.txt" with { type: "file" }
import skill_125 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/all_upload_fuzz.txt" with { type: "file" }
import skill_126 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/apache_upload_fuzz.txt" with { type: "file" }
import skill_127 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/asp_upload_fuzz.txt" with { type: "file" }
import skill_128 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/iis_upload_fuzz.txt" with { type: "file" }
import skill_129 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/jsp_upload_fuzz.txt" with { type: "file" }
import skill_130 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/linux_upload_fuzz.txt" with { type: "file" }
import skill_131 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/php_upload_fuzz.txt" with { type: "file" }
import skill_132 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/tomcat_upload_fuzz.txt" with { type: "file" }
import skill_133 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/win_upload_fuzz.txt" with { type: "file" }
import skill_134 from "./skills/builtin/fuzz-dicts-skills/userNameDict/ChinaUserName.txt" with { type: "file" }
import skill_135 from "./skills/builtin/fuzz-dicts-skills/userNameDict/test-phone.txt" with { type: "file" }
import skill_136 from "./skills/builtin/fuzz-dicts-skills/userNameDict/top300_lastname.txt" with { type: "file" }
import skill_137 from "./skills/builtin/fuzz-dicts-skills/userNameDict/top500.txt" with { type: "file" }
import skill_138 from "./skills/builtin/fuzz-dicts-skills/userNameDict/user.txt" with { type: "file" }
import skill_139 from "./skills/builtin/fuzz-dicts-skills/userNameDict/中文姓名(简写、全拼).txt" with { type: "file" }
import skill_140 from "./skills/builtin/fuzz-dicts-skills/userNameDict/常用用户名.txt" with { type: "file" }
import skill_141 from "./skills/builtin/known-product-exploit/SKILL.md" with { type: "file" }
import skill_142 from "./skills/builtin/nuclei-skill/SKILL.md" with { type: "file" }
import skill_143 from "./skills/builtin/nuclei-skill/evals/evals.json" with { type: "file" }
import skill_144 from "./skills/builtin/payload-research/SKILL.md" with { type: "file" }
import skill_145 from "./skills/builtin/payloads-everything/SKILL.md" with { type: "file" }
import skill_146 from "./skills/builtin/payloads-everything/references/API Key Leaks/Files/MachineKeys.txt" with { type: "file" }
import skill_147 from "./skills/builtin/payloads-everything/references/API Key Leaks/IIS-Machine-Keys.md" with { type: "file" }
import skill_148 from "./skills/builtin/payloads-everything/references/API Key Leaks/README.md" with { type: "file" }
import skill_149 from "./skills/builtin/payloads-everything/references/Account Takeover/README.md" with { type: "file" }
import skill_150 from "./skills/builtin/payloads-everything/references/Account Takeover/mfa-bypass.md" with { type: "file" }
import skill_151 from "./skills/builtin/payloads-everything/references/Brute Force Rate Limit/README.md" with { type: "file" }
import skill_152 from "./skills/builtin/payloads-everything/references/Business Logic Errors/README.md" with { type: "file" }
import skill_153 from "./skills/builtin/payloads-everything/references/CORS Misconfiguration/README.md" with { type: "file" }
import skill_154 from "./skills/builtin/payloads-everything/references/CRLF Injection/Files/crlfinjection.txt" with { type: "file" }
import skill_155 from "./skills/builtin/payloads-everything/references/CRLF Injection/README.md" with { type: "file" }
import skill_156 from "./skills/builtin/payloads-everything/references/CSS Injection/README.md" with { type: "file" }
import skill_157 from "./skills/builtin/payloads-everything/references/CSV Injection/README.md" with { type: "file" }
import skill_158 from "./skills/builtin/payloads-everything/references/CVE Exploits/Log4Shell.md" with { type: "file" }
import skill_159 from "./skills/builtin/payloads-everything/references/CVE Exploits/README.md" with { type: "file" }
import skill_160 from "./skills/builtin/payloads-everything/references/Clickjacking/README.md" with { type: "file" }
import skill_161 from "./skills/builtin/payloads-everything/references/Client Side Path Traversal/README.md" with { type: "file" }
import skill_162 from "./skills/builtin/payloads-everything/references/Command Injection/Intruder/command-execution-unix.txt" with { type: "file" }
import skill_163 from "./skills/builtin/payloads-everything/references/Command Injection/Intruder/command_exec.txt" with { type: "file" }
import skill_164 from "./skills/builtin/payloads-everything/references/Command Injection/README.md" with { type: "file" }
import skill_165 from "./skills/builtin/payloads-everything/references/Cross-Site Request Forgery/README.md" with { type: "file" }
import skill_166 from "./skills/builtin/payloads-everything/references/DNS Rebinding/README.md" with { type: "file" }
import skill_167 from "./skills/builtin/payloads-everything/references/DOM Clobbering/README.md" with { type: "file" }
import skill_168 from "./skills/builtin/payloads-everything/references/Denial of Service/README.md" with { type: "file" }
import skill_169 from "./skills/builtin/payloads-everything/references/Dependency Confusion/README.md" with { type: "file" }
import skill_170 from "./skills/builtin/payloads-everything/references/Directory Traversal/Intruder/deep_traversal.txt" with { type: "file" }
import skill_171 from "./skills/builtin/payloads-everything/references/Directory Traversal/Intruder/directory_traversal.txt" with { type: "file" }
import skill_172 from "./skills/builtin/payloads-everything/references/Directory Traversal/Intruder/dotdotpwn.txt" with { type: "file" }
import skill_173 from "./skills/builtin/payloads-everything/references/Directory Traversal/Intruder/traversals-8-deep-exotic-encoding.txt" with { type: "file" }
import skill_174 from "./skills/builtin/payloads-everything/references/Directory Traversal/README.md" with { type: "file" }
import skill_175 from "./skills/builtin/payloads-everything/references/Encoding Transformations/README.md" with { type: "file" }
import skill_176 from "./skills/builtin/payloads-everything/references/External Variable Modification/README.md" with { type: "file" }
import skill_177 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/BSD-files.txt" with { type: "file" }
import skill_178 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/JHADDIX_LFI.txt" with { type: "file" }
import skill_179 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/LFI-FD-check.txt" with { type: "file" }
import skill_180 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/LFI-WindowsFileCheck.txt" with { type: "file" }
import skill_181 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/Linux-files.txt" with { type: "file" }
import skill_182 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/List_Of_File_To_Include.txt" with { type: "file" }
import skill_183 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/List_Of_File_To_Include_NullByteAdded.txt" with { type: "file" }
import skill_184 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/Mac-files.txt" with { type: "file" }
import skill_185 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/Traversal.txt" with { type: "file" }
import skill_186 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/Web-files.txt" with { type: "file" }
import skill_187 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/Windows-files.txt" with { type: "file" }
import skill_188 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/dot-slash-PathTraversal_and_LFI_pairing.txt" with { type: "file" }
import skill_189 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/php-filter-iconv.txt" with { type: "file" }
import skill_190 from "./skills/builtin/payloads-everything/references/File Inclusion/Intruders/simple-check.txt" with { type: "file" }
import skill_191 from "./skills/builtin/payloads-everything/references/File Inclusion/LFI-to-RCE.md" with { type: "file" }
import skill_192 from "./skills/builtin/payloads-everything/references/File Inclusion/README.md" with { type: "file" }
import skill_193 from "./skills/builtin/payloads-everything/references/File Inclusion/Wrappers.md" with { type: "file" }
import skill_194 from "./skills/builtin/payloads-everything/references/Google Web Toolkit/README.md" with { type: "file" }
import skill_195 from "./skills/builtin/payloads-everything/references/GraphQL Injection/README.md" with { type: "file" }
import skill_196 from "./skills/builtin/payloads-everything/references/HTTP Parameter Pollution/README.md" with { type: "file" }
import skill_197 from "./skills/builtin/payloads-everything/references/Hidden Parameters/README.md" with { type: "file" }
import skill_198 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/DotNET.md" with { type: "file" }
import skill_199 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/Files/ruby-serialize.yaml" with { type: "file" }
import skill_200 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/Java.md" with { type: "file" }
import skill_201 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/Node.md" with { type: "file" }
import skill_202 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/PHP.md" with { type: "file" }
import skill_203 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/Python.md" with { type: "file" }
import skill_204 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/README.md" with { type: "file" }
import skill_205 from "./skills/builtin/payloads-everything/references/Insecure Deserialization/Ruby.md" with { type: "file" }
import skill_206 from "./skills/builtin/payloads-everything/references/Insecure Direct Object References/README.md" with { type: "file" }
import skill_207 from "./skills/builtin/payloads-everything/references/Insecure Management Interface/Intruder/springboot_actuator.txt" with { type: "file" }
import skill_208 from "./skills/builtin/payloads-everything/references/Insecure Management Interface/README.md" with { type: "file" }
import skill_209 from "./skills/builtin/payloads-everything/references/Insecure Randomness/README.md" with { type: "file" }
import skill_210 from "./skills/builtin/payloads-everything/references/JSON Web Token/README.md" with { type: "file" }
import skill_211 from "./skills/builtin/payloads-everything/references/Java RMI/README.md" with { type: "file" }
import skill_212 from "./skills/builtin/payloads-everything/references/LDAP Injection/Intruder/LDAP_FUZZ.txt" with { type: "file" }
import skill_213 from "./skills/builtin/payloads-everything/references/LDAP Injection/Intruder/LDAP_FUZZ_SMALL.txt" with { type: "file" }
import skill_214 from "./skills/builtin/payloads-everything/references/LDAP Injection/Intruder/LDAP_attributes.txt" with { type: "file" }
import skill_215 from "./skills/builtin/payloads-everything/references/LDAP Injection/README.md" with { type: "file" }
import skill_216 from "./skills/builtin/payloads-everything/references/LaTeX Injection/README.md" with { type: "file" }
import skill_217 from "./skills/builtin/payloads-everything/references/Mass Assignment/README.md" with { type: "file" }
import skill_218 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Active Directory Attack.md" with { type: "file" }
import skill_219 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Bind Shell Cheatsheet.md" with { type: "file" }
import skill_220 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Cloud - AWS Pentest.md" with { type: "file" }
import skill_221 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Cloud - Azure Pentest.md" with { type: "file" }
import skill_222 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Cobalt Strike - Cheatsheet.md" with { type: "file" }
import skill_223 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Container - Docker Pentest.md" with { type: "file" }
import skill_224 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Container - Kubernetes Pentest.md" with { type: "file" }
import skill_225 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Escape Breakout.md" with { type: "file" }
import skill_226 from "./skills/builtin/payloads-everything/references/Methodology and Resources/HTML Smuggling.md" with { type: "file" }
import skill_227 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Hash Cracking.md" with { type: "file" }
import skill_228 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Initial Access.md" with { type: "file" }
import skill_229 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Linux - Evasion.md" with { type: "file" }
import skill_230 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Linux - Persistence.md" with { type: "file" }
import skill_231 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Linux - Privilege Escalation.md" with { type: "file" }
import skill_232 from "./skills/builtin/payloads-everything/references/Methodology and Resources/MSSQL Server - Cheatsheet.md" with { type: "file" }
import skill_233 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Metasploit - Cheatsheet.md" with { type: "file" }
import skill_234 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Methodology and enumeration.md" with { type: "file" }
import skill_235 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Network Discovery.md" with { type: "file" }
import skill_236 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Network Pivoting Techniques.md" with { type: "file" }
import skill_237 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Office - Attacks.md" with { type: "file" }
import skill_238 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Powershell - Cheatsheet.md" with { type: "file" }
import skill_239 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Reverse Shell Cheatsheet.md" with { type: "file" }
import skill_240 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Source Code Management.md" with { type: "file" }
import skill_241 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Vulnerability Reports.md" with { type: "file" }
import skill_242 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Web Attack Surface.md" with { type: "file" }
import skill_243 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - AMSI Bypass.md" with { type: "file" }
import skill_244 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - DPAPI.md" with { type: "file" }
import skill_245 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - Defenses.md" with { type: "file" }
import skill_246 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - Download and Execute.md" with { type: "file" }
import skill_247 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - Mimikatz.md" with { type: "file" }
import skill_248 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - Persistence.md" with { type: "file" }
import skill_249 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - Privilege Escalation.md" with { type: "file" }
import skill_250 from "./skills/builtin/payloads-everything/references/Methodology and Resources/Windows - Using credentials.md" with { type: "file" }
import skill_251 from "./skills/builtin/payloads-everything/references/NoSQL Injection/Intruder/MongoDB.txt" with { type: "file" }
import skill_252 from "./skills/builtin/payloads-everything/references/NoSQL Injection/Intruder/NoSQL.txt" with { type: "file" }
import skill_253 from "./skills/builtin/payloads-everything/references/NoSQL Injection/README.md" with { type: "file" }
import skill_254 from "./skills/builtin/payloads-everything/references/OAuth Misconfiguration/README.md" with { type: "file" }
import skill_255 from "./skills/builtin/payloads-everything/references/ORM Leak/README.md" with { type: "file" }
import skill_256 from "./skills/builtin/payloads-everything/references/Open Redirect/Intruder/Open-Redirect-payloads.txt" with { type: "file" }
import skill_257 from "./skills/builtin/payloads-everything/references/Open Redirect/Intruder/open_redirect_wordlist.txt" with { type: "file" }
import skill_258 from "./skills/builtin/payloads-everything/references/Open Redirect/Intruder/openredirects.txt" with { type: "file" }
import skill_259 from "./skills/builtin/payloads-everything/references/Open Redirect/README.md" with { type: "file" }
import skill_260 from "./skills/builtin/payloads-everything/references/Prototype Pollution/README.md" with { type: "file" }
import skill_261 from "./skills/builtin/payloads-everything/references/Race Condition/README.md" with { type: "file" }
import skill_262 from "./skills/builtin/payloads-everything/references/Regular Expression/README.md" with { type: "file" }
import skill_263 from "./skills/builtin/payloads-everything/references/Request Smuggling/README.md" with { type: "file" }
import skill_264 from "./skills/builtin/payloads-everything/references/Reverse Proxy Misconfigurations/README.md" with { type: "file" }
import skill_265 from "./skills/builtin/payloads-everything/references/SAML Injection/README.md" with { type: "file" }
import skill_266 from "./skills/builtin/payloads-everything/references/SQL Injection/BigQuery Injection.md" with { type: "file" }
import skill_267 from "./skills/builtin/payloads-everything/references/SQL Injection/Cassandra Injection.md" with { type: "file" }
import skill_268 from "./skills/builtin/payloads-everything/references/SQL Injection/DB2 Injection.md" with { type: "file" }
import skill_269 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/Auth_Bypass.txt" with { type: "file" }
import skill_270 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/Auth_Bypass2.txt" with { type: "file" }
import skill_271 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_MSSQL-WHERE_Time.txt" with { type: "file" }
import skill_272 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_MSSQL.txt" with { type: "file" }
import skill_273 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_MSSQL_Enumeration.txt" with { type: "file" }
import skill_274 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_MYSQL.txt" with { type: "file" }
import skill_275 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_MySQL-WHERE_Time.txt" with { type: "file" }
import skill_276 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_MySQL_ReadLocalFiles.txt" with { type: "file" }
import skill_277 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_Oracle.txt" with { type: "file" }
import skill_278 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/FUZZDB_Postgres_Enumeration.txt" with { type: "file" }
import skill_279 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/Generic_ErrorBased.txt" with { type: "file" }
import skill_280 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/Generic_Fuzz.txt" with { type: "file" }
import skill_281 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/Generic_TimeBased.txt" with { type: "file" }
import skill_282 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/Generic_UnionSelect.txt" with { type: "file" }
import skill_283 from "./skills/builtin/payloads-everything/references/SQL Injection/Intruder/SQLi_Polyglots.txt" with { type: "file" }
import skill_284 from "./skills/builtin/payloads-everything/references/SQL Injection/MSSQL Injection.md" with { type: "file" }
import skill_285 from "./skills/builtin/payloads-everything/references/SQL Injection/MySQL Injection.md" with { type: "file" }
import skill_286 from "./skills/builtin/payloads-everything/references/SQL Injection/OracleSQL Injection.md" with { type: "file" }
import skill_287 from "./skills/builtin/payloads-everything/references/SQL Injection/PostgreSQL Injection.md" with { type: "file" }
import skill_288 from "./skills/builtin/payloads-everything/references/SQL Injection/README.md" with { type: "file" }
import skill_289 from "./skills/builtin/payloads-everything/references/SQL Injection/SQLite Injection.md" with { type: "file" }
import skill_290 from "./skills/builtin/payloads-everything/references/SQL Injection/SQLmap.md" with { type: "file" }
import skill_291 from "./skills/builtin/payloads-everything/references/Server Side Include Injection/Files/ssi_esi.txt" with { type: "file" }
import skill_292 from "./skills/builtin/payloads-everything/references/Server Side Include Injection/README.md" with { type: "file" }
import skill_293 from "./skills/builtin/payloads-everything/references/Server Side Request Forgery/README.md" with { type: "file" }
import skill_294 from "./skills/builtin/payloads-everything/references/Server Side Request Forgery/SSRF-Advanced-Exploitation.md" with { type: "file" }
import skill_295 from "./skills/builtin/payloads-everything/references/Server Side Request Forgery/SSRF-Cloud-Instances.md" with { type: "file" }
import skill_296 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/ASP.md" with { type: "file" }
import skill_297 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/Elixir.md" with { type: "file" }
import skill_298 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/Java.md" with { type: "file" }
import skill_299 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/JavaScript.md" with { type: "file" }
import skill_300 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/PHP.md" with { type: "file" }
import skill_301 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/Python.md" with { type: "file" }
import skill_302 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/README.md" with { type: "file" }
import skill_303 from "./skills/builtin/payloads-everything/references/Server Side Template Injection/Ruby.md" with { type: "file" }
import skill_304 from "./skills/builtin/payloads-everything/references/Tabnabbing/README.md" with { type: "file" }
import skill_305 from "./skills/builtin/payloads-everything/references/Type Juggling/README.md" with { type: "file" }
import skill_306 from "./skills/builtin/payloads-everything/references/Upload Insecure Files/CVE ZIP Symbolic Link/generate.sh" with { type: "file" }
import skill_307 from "./skills/builtin/payloads-everything/references/Upload Insecure Files/Configuration Apache .htaccess/README.md" with { type: "file" }
import skill_308 from "./skills/builtin/payloads-everything/references/Upload Insecure Files/EICAR/eicar.txt" with { type: "file" }
import skill_309 from "./skills/builtin/payloads-everything/references/Upload Insecure Files/README.md" with { type: "file" }
import skill_310 from "./skills/builtin/payloads-everything/references/Virtual Hosts/README.md" with { type: "file" }
import skill_311 from "./skills/builtin/payloads-everything/references/Web Cache Deception/Intruders/param_miner_lowercase_headers.txt" with { type: "file" }
import skill_312 from "./skills/builtin/payloads-everything/references/Web Cache Deception/README.md" with { type: "file" }
import skill_313 from "./skills/builtin/payloads-everything/references/Web Sockets/README.md" with { type: "file" }
import skill_314 from "./skills/builtin/payloads-everything/references/XPATH Injection/README.md" with { type: "file" }
import skill_315 from "./skills/builtin/payloads-everything/references/XS-Leak/README.md" with { type: "file" }
import skill_316 from "./skills/builtin/payloads-everything/references/XSLT Injection/README.md" with { type: "file" }
import skill_317 from "./skills/builtin/payloads-everything/references/XSS Injection/1 - XSS Filter Bypass.md" with { type: "file" }
import skill_318 from "./skills/builtin/payloads-everything/references/XSS Injection/2 - XSS Polyglot.md" with { type: "file" }
import skill_319 from "./skills/builtin/payloads-everything/references/XSS Injection/3 - XSS Common WAF Bypass.md" with { type: "file" }
import skill_320 from "./skills/builtin/payloads-everything/references/XSS Injection/4 - CSP Bypass.md" with { type: "file" }
import skill_321 from "./skills/builtin/payloads-everything/references/XSS Injection/5 - XSS in Angular.md" with { type: "file" }
import skill_322 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/0xcela_event_handlers.txt" with { type: "file" }
import skill_323 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/BRUTELOGIC-XSS-JS.txt" with { type: "file" }
import skill_324 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/BRUTELOGIC-XSS-STRINGS.txt" with { type: "file" }
import skill_325 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/IntrudersXSS.txt" with { type: "file" }
import skill_326 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/JHADDIX_XSS.txt" with { type: "file" }
import skill_327 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/MarioXSSVectors.txt" with { type: "file" }
import skill_328 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/RSNAKE_XSS.txt" with { type: "file" }
import skill_329 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/XSSDetection.txt" with { type: "file" }
import skill_330 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/XSS_Polyglots.txt" with { type: "file" }
import skill_331 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/jsonp_endpoint.txt" with { type: "file" }
import skill_332 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/port_swigger_xss_cheatsheet_event_handlers.txt" with { type: "file" }
import skill_333 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/xss_alert.txt" with { type: "file" }
import skill_334 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/xss_alert_identifiable.txt" with { type: "file" }
import skill_335 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/xss_payloads_quick.txt" with { type: "file" }
import skill_336 from "./skills/builtin/payloads-everything/references/XSS Injection/Intruders/xss_swf_fuzz.txt" with { type: "file" }
import skill_337 from "./skills/builtin/payloads-everything/references/XSS Injection/README.md" with { type: "file" }
import skill_338 from "./skills/builtin/payloads-everything/references/XXE Injection/Intruders/XXE_Fuzzing.txt" with { type: "file" }
import skill_339 from "./skills/builtin/payloads-everything/references/XXE Injection/Intruders/xml-attacks.txt" with { type: "file" }
import skill_340 from "./skills/builtin/payloads-everything/references/XXE Injection/README.md" with { type: "file" }
import skill_341 from "./skills/builtin/payloads-everything/references/Zip Slip/README.md" with { type: "file" }
import skill_342 from "./skills/builtin/pentest-fuzz-skill/README.md" with { type: "file" }
import skill_343 from "./skills/builtin/pentest-fuzz-skill/SKILL.md" with { type: "file" }
import skill_344 from "./skills/builtin/pentest-fuzz-skill/deserialization/README.md" with { type: "file" }
import skill_345 from "./skills/builtin/pentest-fuzz-skill/deserialization/fuzz.txt" with { type: "file" }
import skill_346 from "./skills/builtin/pentest-fuzz-skill/deserialization/fuzzing.md" with { type: "file" }
import skill_347 from "./skills/builtin/pentest-fuzz-skill/deserialization/overview.md" with { type: "file" }
import skill_348 from "./skills/builtin/pentest-fuzz-skill/evals/evals.json" with { type: "file" }
import skill_349 from "./skills/builtin/pentest-fuzz-skill/idor/README.md" with { type: "file" }
import skill_350 from "./skills/builtin/pentest-fuzz-skill/idor/fuzz.txt" with { type: "file" }
import skill_351 from "./skills/builtin/pentest-fuzz-skill/idor/fuzzing.md" with { type: "file" }
import skill_352 from "./skills/builtin/pentest-fuzz-skill/idor/overview.md" with { type: "file" }
import skill_353 from "./skills/builtin/pentest-fuzz-skill/jwt/README.md" with { type: "file" }
import skill_354 from "./skills/builtin/pentest-fuzz-skill/jwt/fuzz.txt" with { type: "file" }
import skill_355 from "./skills/builtin/pentest-fuzz-skill/jwt/fuzzing.md" with { type: "file" }
import skill_356 from "./skills/builtin/pentest-fuzz-skill/jwt/overview.md" with { type: "file" }
import skill_357 from "./skills/builtin/pentest-fuzz-skill/lfi-rfi/README.md" with { type: "file" }
import skill_358 from "./skills/builtin/pentest-fuzz-skill/lfi-rfi/fuzz.txt" with { type: "file" }
import skill_359 from "./skills/builtin/pentest-fuzz-skill/lfi-rfi/fuzzing.md" with { type: "file" }
import skill_360 from "./skills/builtin/pentest-fuzz-skill/lfi-rfi/overview.md" with { type: "file" }
import skill_361 from "./skills/builtin/pentest-fuzz-skill/rce/README.md" with { type: "file" }
import skill_362 from "./skills/builtin/pentest-fuzz-skill/rce/fuzz.txt" with { type: "file" }
import skill_363 from "./skills/builtin/pentest-fuzz-skill/rce/fuzzing.md" with { type: "file" }
import skill_364 from "./skills/builtin/pentest-fuzz-skill/rce/overview.md" with { type: "file" }
import skill_365 from "./skills/builtin/pentest-fuzz-skill/sqli/README.md" with { type: "file" }
import skill_366 from "./skills/builtin/pentest-fuzz-skill/sqli/fuzz.txt" with { type: "file" }
import skill_367 from "./skills/builtin/pentest-fuzz-skill/sqli/fuzzing.md" with { type: "file" }
import skill_368 from "./skills/builtin/pentest-fuzz-skill/sqli/overview.md" with { type: "file" }
import skill_369 from "./skills/builtin/pentest-fuzz-skill/ssrf/README.md" with { type: "file" }
import skill_370 from "./skills/builtin/pentest-fuzz-skill/ssrf/fuzz.txt" with { type: "file" }
import skill_371 from "./skills/builtin/pentest-fuzz-skill/ssrf/fuzzing.md" with { type: "file" }
import skill_372 from "./skills/builtin/pentest-fuzz-skill/ssrf/overview.md" with { type: "file" }
import skill_373 from "./skills/builtin/pentest-fuzz-skill/ssti/README.md" with { type: "file" }
import skill_374 from "./skills/builtin/pentest-fuzz-skill/ssti/fuzz.txt" with { type: "file" }
import skill_375 from "./skills/builtin/pentest-fuzz-skill/ssti/fuzzing.md" with { type: "file" }
import skill_376 from "./skills/builtin/pentest-fuzz-skill/ssti/overview.md" with { type: "file" }
import skill_377 from "./skills/builtin/pentest-fuzz-skill/xss/README.md" with { type: "file" }
import skill_378 from "./skills/builtin/pentest-fuzz-skill/xss/fuzz.txt" with { type: "file" }
import skill_379 from "./skills/builtin/pentest-fuzz-skill/xss/fuzzing.md" with { type: "file" }
import skill_380 from "./skills/builtin/pentest-fuzz-skill/xss/overview.md" with { type: "file" }
import skill_381 from "./skills/builtin/pentest-fuzz-skill/xxe/README.md" with { type: "file" }
import skill_382 from "./skills/builtin/pentest-fuzz-skill/xxe/fuzz.txt" with { type: "file" }
import skill_383 from "./skills/builtin/pentest-fuzz-skill/xxe/fuzzing.md" with { type: "file" }
import skill_384 from "./skills/builtin/pentest-fuzz-skill/xxe/overview.md" with { type: "file" }
import skill_385 from "./skills/builtin/pentest/SKILL.md" with { type: "file" }
import skill_386 from "./skills/builtin/pentest/references/automation.md" with { type: "file" }
import skill_387 from "./skills/builtin/pentest/references/binary-audit.md" with { type: "file" }
import skill_388 from "./skills/builtin/pentest/references/custom-rules.md" with { type: "file" }
import skill_389 from "./skills/builtin/pentest/references/disclosure.md" with { type: "file" }
import skill_390 from "./skills/builtin/pentest/references/external-platforms.md" with { type: "file" }
import skill_391 from "./skills/builtin/pentest/references/fuzzing.md" with { type: "file" }
import skill_392 from "./skills/builtin/pentest/references/hack-skills.md" with { type: "file" }
import skill_393 from "./skills/builtin/pentest/references/mobile-pentest.md" with { type: "file" }
import skill_394 from "./skills/builtin/pentest/references/pentest-self-audit.md" with { type: "file" }
import skill_395 from "./skills/builtin/pentest/references/source-audit.md" with { type: "file" }
import skill_396 from "./skills/builtin/pentest/references/target-selection.md" with { type: "file" }
import skill_397 from "./skills/builtin/recon/SKILL.md" with { type: "file" }
import skill_398 from "./skills/builtin/recon/references/vuln-class-matrix.md" with { type: "file" }
import skill_399 from "./skills/builtin/remote-cmd-execution/SKILL.md" with { type: "file" }
import skill_400 from "./skills/builtin/targeted-pentest/SKILL.md" with { type: "file" }
import skill_401 from "./skills/builtin/targeted-pentest/references/auth-and-access.md" with { type: "file" }
import skill_402 from "./skills/builtin/targeted-pentest/references/auth-infra.md" with { type: "file" }
import skill_403 from "./skills/builtin/targeted-pentest/references/auth-jwt.md" with { type: "file" }
import skill_404 from "./skills/builtin/targeted-pentest/references/client-side-advanced.md" with { type: "file" }
import skill_405 from "./skills/builtin/targeted-pentest/references/client-side.md" with { type: "file" }
import skill_406 from "./skills/builtin/targeted-pentest/references/cves.md" with { type: "file" }
import skill_407 from "./skills/builtin/targeted-pentest/references/field-notes.md" with { type: "file" }
import skill_408 from "./skills/builtin/targeted-pentest/references/node-and-prototype.md" with { type: "file" }
import skill_409 from "./skills/builtin/targeted-pentest/references/server-side-advanced-2.md" with { type: "file" }
import skill_410 from "./skills/builtin/targeted-pentest/references/server-side-advanced.md" with { type: "file" }
import skill_411 from "./skills/builtin/targeted-pentest/references/server-side-deser.md" with { type: "file" }
import skill_412 from "./skills/builtin/targeted-pentest/references/server-side-exec-2.md" with { type: "file" }
import skill_413 from "./skills/builtin/targeted-pentest/references/server-side-exec.md" with { type: "file" }
import skill_414 from "./skills/builtin/targeted-pentest/references/server-side.md" with { type: "file" }
import skill_415 from "./skills/builtin/targeted-pentest/references/sql-injection.md" with { type: "file" }
import runtime_0 from "../runtime/assets/Dockerfile" with { type: "file" }
import runtime_1 from "../runtime/assets/provision-pentest-vps.sh" with { type: "file" }

export const BUILTIN_PROMPTS = {
    "CHALLENGE_PLANNER.md": prompt_0,
    "KALI_PROVISIONER.md": prompt_1,
    "OBJECTIVE_VERIFIER.md": prompt_2,
    "VULN_RESEARCHER.md": prompt_3,
    "kimi-security.md": prompt_4,
} as const

export const BUILTIN_SKILL_FILES = {
    "ffuf-skill/SKILL.md": skill_0,
    "ffuf-skill/references/ffuf-web-params.md": skill_1,
    "fuzz-dicts-skills/README.md": skill_2,
    "fuzz-dicts-skills/SKILL.md": skill_3,
    "fuzz-dicts-skills/XXEDicts/README.MD": skill_4,
    "fuzz-dicts-skills/apiDict/api.txt": skill_5,
    "fuzz-dicts-skills/ctfDict/ctf-wscan/README.md": skill_6,
    "fuzz-dicts-skills/ctfDict/ctf-wscan/dict/default.txt": skill_7,
    "fuzz-dicts-skills/ctfDict/ctf-wscan/dict/ext.txt": skill_8,
    "fuzz-dicts-skills/ctfDict/ctf.txt": skill_9,
    "fuzz-dicts-skills/directoryDicts/Filenames_or_Directories_All.txt": skill_10,
    "fuzz-dicts-skills/directoryDicts/admin变种.txt": skill_11,
    "fuzz-dicts-skills/directoryDicts/asp/top30000.txt": skill_12,
    "fuzz-dicts-skills/directoryDicts/dicc.txt": skill_13,
    "fuzz-dicts-skills/directoryDicts/en_dirctories_all.txt": skill_14,
    "fuzz-dicts-skills/directoryDicts/fileName10000.txt": skill_15,
    "fuzz-dicts-skills/directoryDicts/jsp/top100.txt": skill_16,
    "fuzz-dicts-skills/directoryDicts/php/phpFileName.txt": skill_17,
    "fuzz-dicts-skills/directoryDicts/php/top3000.txt": skill_18,
    "fuzz-dicts-skills/directoryDicts/top7000.txt": skill_19,
    "fuzz-dicts-skills/directoryDicts/vulns.txt": skill_20,
    "fuzz-dicts-skills/directoryDicts/vuls/LDAP.txt": skill_21,
    "fuzz-dicts-skills/directoryDicts/vuls/Traversal.txt": skill_22,
    "fuzz-dicts-skills/directoryDicts/vuls/XML.txt": skill_23,
    "fuzz-dicts-skills/directoryDicts/vuls/XXEExploit.txt": skill_24,
    "fuzz-dicts-skills/directoryDicts/vuls/all.txt": skill_25,
    "fuzz-dicts-skills/directoryDicts/vuls/apache.txt": skill_26,
    "fuzz-dicts-skills/directoryDicts/vuls/cgis.txt": skill_27,
    "fuzz-dicts-skills/directoryDicts/vuls/coldfusion.txt": skill_28,
    "fuzz-dicts-skills/directoryDicts/vuls/domino.txt": skill_29,
    "fuzz-dicts-skills/directoryDicts/vuls/fatwire.txt": skill_30,
    "fuzz-dicts-skills/directoryDicts/vuls/fatwire_pagenames.txt": skill_31,
    "fuzz-dicts-skills/directoryDicts/vuls/frontpage.txt": skill_32,
    "fuzz-dicts-skills/directoryDicts/vuls/iis.txt": skill_33,
    "fuzz-dicts-skills/directoryDicts/vuls/iplanet.txt": skill_34,
    "fuzz-dicts-skills/directoryDicts/vuls/jrun.txt": skill_35,
    "fuzz-dicts-skills/directoryDicts/vuls/netware.txt": skill_36,
    "fuzz-dicts-skills/directoryDicts/vuls/oracle9i.txt": skill_37,
    "fuzz-dicts-skills/directoryDicts/vuls/sharepoint.txt": skill_38,
    "fuzz-dicts-skills/directoryDicts/vuls/sunas.txt": skill_39,
    "fuzz-dicts-skills/directoryDicts/vuls/tests.txt": skill_40,
    "fuzz-dicts-skills/directoryDicts/vuls/tomcat.txt": skill_41,
    "fuzz-dicts-skills/directoryDicts/vuls/vignette.txt": skill_42,
    "fuzz-dicts-skills/directoryDicts/vuls/weblogic.txt": skill_43,
    "fuzz-dicts-skills/directoryDicts/vuls/websphere.txt": skill_44,
    "fuzz-dicts-skills/easyXssPayload/README.md": skill_45,
    "fuzz-dicts-skills/easyXssPayload/burpXssPayload.txt": skill_46,
    "fuzz-dicts-skills/easyXssPayload/easyXssPayload.txt": skill_47,
    "fuzz-dicts-skills/easyXssPayload/markdown-xss-payload.txt": skill_48,
    "fuzz-dicts-skills/evals/evals.json": skill_49,
    "fuzz-dicts-skills/images/README.MD": skill_50,
    "fuzz-dicts-skills/js/jsFileDict.txt": skill_51,
    "fuzz-dicts-skills/lotDict/acount.txt": skill_52,
    "fuzz-dicts-skills/lotDict/password.txt": skill_53,
    "fuzz-dicts-skills/paramDict/AllParam.txt": skill_54,
    "fuzz-dicts-skills/paramDict/Arjun/CHANGELOG.md": skill_55,
    "fuzz-dicts-skills/paramDict/Arjun/README.md": skill_56,
    "fuzz-dicts-skills/paramDict/Arjun/db/params.txt": skill_57,
    "fuzz-dicts-skills/paramDict/burp.txt": skill_58,
    "fuzz-dicts-skills/paramDict/dir.txt": skill_59,
    "fuzz-dicts-skills/paramDict/js.txt": skill_60,
    "fuzz-dicts-skills/paramDict/parameter.txt": skill_61,
    "fuzz-dicts-skills/paramDict/php.txt": skill_62,
    "fuzz-dicts-skills/paramDict/vars.txt": skill_63,
    "fuzz-dicts-skills/passwordDict/Middleware/axis.txt": skill_64,
    "fuzz-dicts-skills/passwordDict/Middleware/tomcat-pass.txt": skill_65,
    "fuzz-dicts-skills/passwordDict/Middleware/tomcat-user.txt": skill_66,
    "fuzz-dicts-skills/passwordDict/Middleware/weblogic.txt": skill_67,
    "fuzz-dicts-skills/passwordDict/Middleware/zabbix.txt": skill_68,
    "fuzz-dicts-skills/passwordDict/README.MD": skill_69,
    "fuzz-dicts-skills/passwordDict/RW_Password/README.md": skill_70,
    "fuzz-dicts-skills/passwordDict/RW_Password/四个条件至少满足三个的6位数密码107965条.txt": skill_71,
    "fuzz-dicts-skills/passwordDict/RW_Password/四个条件至少满足三个的8位数密码91286条.txt": skill_72,
    "fuzz-dicts-skills/passwordDict/RW_Password/数字和字母同时存在的6位数密码76905条.txt": skill_73,
    "fuzz-dicts-skills/passwordDict/RW_Password/数字和字母同时存在的8位数密码60850条.txt": skill_74,
    "fuzz-dicts-skills/passwordDict/RW_Password/符合四个条件的6位数密码1633条.txt": skill_75,
    "fuzz-dicts-skills/passwordDict/RW_Password/符合四个条件的8位数密码1420条.txt": skill_76,
    "fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字不能有三个相同的字符和特殊符号的6位数密码76905条.txt": skill_77,
    "fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字不能有三个相同的字符和特殊符号的8位数密码60850条.txt": skill_78,
    "fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字的6位数密码75945条.txt": skill_79,
    "fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个大写字母一个小写字母一个数字的8位数密码59995条.txt": skill_80,
    "fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个字母一个数字一个特殊符号的6位数密码27566条.txt": skill_81,
    "fuzz-dicts-skills/passwordDict/RW_Password/至少存在一个字母一个数字一个特殊符号的8位数密码26860条.txt": skill_82,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/ftp/init.txt": skill_83,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/ftp弱口令/ftp-pass.txt": skill_84,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/ftp弱口令/ftp-user.txt": skill_85,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/mstsc远程弱口令/3389.txt": skill_86,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/mysql弱口令/mysql-pass.txt": skill_87,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/mysql弱口令/mysql-user.txt": skill_88,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/ssh弱口令/ssh-pass.txt": skill_89,
    "fuzz-dicts-skills/passwordDict/ServiceWeakPass/ssh弱口令/ssh-user.txt": skill_90,
    "fuzz-dicts-skills/passwordDict/birth.txt": skill_91,
    "fuzz-dicts-skills/passwordDict/top1000.txt": skill_92,
    "fuzz-dicts-skills/passwordDict/top19576.txt": skill_93,
    "fuzz-dicts-skills/passwordDict/top3000.txt": skill_94,
    "fuzz-dicts-skills/passwordDict/top500.txt": skill_95,
    "fuzz-dicts-skills/passwordDict/top6000.txt": skill_96,
    "fuzz-dicts-skills/passwordDict/webshell-pass.txt": skill_97,
    "fuzz-dicts-skills/passwordDict/wifi_top2000_passwd.txt": skill_98,
    "fuzz-dicts-skills/passwordDict/某集团下发的弱口令字典.txt": skill_99,
    "fuzz-dicts-skills/passwordDict/路由器默认密码.txt": skill_100,
    "fuzz-dicts-skills/rcePayloads/GhostScript-Rce.txt": skill_101,
    "fuzz-dicts-skills/rcePayloads/Imagemagick-rce.txt": skill_102,
    "fuzz-dicts-skills/rcePayloads/RCE-filter-and-WAF-Bypass.txt": skill_103,
    "fuzz-dicts-skills/rcePayloads/README.md": skill_104,
    "fuzz-dicts-skills/rcePayloads/Top-46-RCE-Parameters.txt": skill_105,
    "fuzz-dicts-skills/rcePayloads/Unix-Commond-Inject-Payload-List.txt": skill_106,
    "fuzz-dicts-skills/rcePayloads/Windows-Commond-Inject-Payload-List.txt": skill_107,
    "fuzz-dicts-skills/rcePayloads/rce-when-all-dangerous-characters-are-escaped.txt": skill_108,
    "fuzz-dicts-skills/references/navigation.md": skill_109,
    "fuzz-dicts-skills/references/tool-playbooks.md": skill_110,
    "fuzz-dicts-skills/routerDicts/README.md": skill_111,
    "fuzz-dicts-skills/routerDicts/pass.txt": skill_112,
    "fuzz-dicts-skills/spring/spring-configuration-metadata.txt": skill_113,
    "fuzz-dicts-skills/sqlDict/sql.txt": skill_114,
    "fuzz-dicts-skills/ssrfDicts/aix_etc.txt": skill_115,
    "fuzz-dicts-skills/ssrfDicts/centsOS_etc.txt": skill_116,
    "fuzz-dicts-skills/ssrfDicts/config.txt": skill_117,
    "fuzz-dicts-skills/ssrfDicts/lfi-scanner.txt": skill_118,
    "fuzz-dicts-skills/ssrfDicts/linux常见路径.txt": skill_119,
    "fuzz-dicts-skills/ssrfDicts/log.txt": skill_120,
    "fuzz-dicts-skills/ssrfDicts/proc.txt": skill_121,
    "fuzz-dicts-skills/ssrfDicts/ssrf.txt": skill_122,
    "fuzz-dicts-skills/subdomainDicts/dic1.txt": skill_123,
    "fuzz-dicts-skills/subdomainDicts/main.txt": skill_124,
    "fuzz-dicts-skills/uploadFileExtDicts/all_upload_fuzz.txt": skill_125,
    "fuzz-dicts-skills/uploadFileExtDicts/apache_upload_fuzz.txt": skill_126,
    "fuzz-dicts-skills/uploadFileExtDicts/asp_upload_fuzz.txt": skill_127,
    "fuzz-dicts-skills/uploadFileExtDicts/iis_upload_fuzz.txt": skill_128,
    "fuzz-dicts-skills/uploadFileExtDicts/jsp_upload_fuzz.txt": skill_129,
    "fuzz-dicts-skills/uploadFileExtDicts/linux_upload_fuzz.txt": skill_130,
    "fuzz-dicts-skills/uploadFileExtDicts/php_upload_fuzz.txt": skill_131,
    "fuzz-dicts-skills/uploadFileExtDicts/tomcat_upload_fuzz.txt": skill_132,
    "fuzz-dicts-skills/uploadFileExtDicts/win_upload_fuzz.txt": skill_133,
    "fuzz-dicts-skills/userNameDict/ChinaUserName.txt": skill_134,
    "fuzz-dicts-skills/userNameDict/test-phone.txt": skill_135,
    "fuzz-dicts-skills/userNameDict/top300_lastname.txt": skill_136,
    "fuzz-dicts-skills/userNameDict/top500.txt": skill_137,
    "fuzz-dicts-skills/userNameDict/user.txt": skill_138,
    "fuzz-dicts-skills/userNameDict/中文姓名(简写、全拼).txt": skill_139,
    "fuzz-dicts-skills/userNameDict/常用用户名.txt": skill_140,
    "known-product-exploit/SKILL.md": skill_141,
    "nuclei-skill/SKILL.md": skill_142,
    "nuclei-skill/evals/evals.json": skill_143,
    "payload-research/SKILL.md": skill_144,
    "payloads-everything/SKILL.md": skill_145,
    "payloads-everything/references/API Key Leaks/Files/MachineKeys.txt": skill_146,
    "payloads-everything/references/API Key Leaks/IIS-Machine-Keys.md": skill_147,
    "payloads-everything/references/API Key Leaks/README.md": skill_148,
    "payloads-everything/references/Account Takeover/README.md": skill_149,
    "payloads-everything/references/Account Takeover/mfa-bypass.md": skill_150,
    "payloads-everything/references/Brute Force Rate Limit/README.md": skill_151,
    "payloads-everything/references/Business Logic Errors/README.md": skill_152,
    "payloads-everything/references/CORS Misconfiguration/README.md": skill_153,
    "payloads-everything/references/CRLF Injection/Files/crlfinjection.txt": skill_154,
    "payloads-everything/references/CRLF Injection/README.md": skill_155,
    "payloads-everything/references/CSS Injection/README.md": skill_156,
    "payloads-everything/references/CSV Injection/README.md": skill_157,
    "payloads-everything/references/CVE Exploits/Log4Shell.md": skill_158,
    "payloads-everything/references/CVE Exploits/README.md": skill_159,
    "payloads-everything/references/Clickjacking/README.md": skill_160,
    "payloads-everything/references/Client Side Path Traversal/README.md": skill_161,
    "payloads-everything/references/Command Injection/Intruder/command-execution-unix.txt": skill_162,
    "payloads-everything/references/Command Injection/Intruder/command_exec.txt": skill_163,
    "payloads-everything/references/Command Injection/README.md": skill_164,
    "payloads-everything/references/Cross-Site Request Forgery/README.md": skill_165,
    "payloads-everything/references/DNS Rebinding/README.md": skill_166,
    "payloads-everything/references/DOM Clobbering/README.md": skill_167,
    "payloads-everything/references/Denial of Service/README.md": skill_168,
    "payloads-everything/references/Dependency Confusion/README.md": skill_169,
    "payloads-everything/references/Directory Traversal/Intruder/deep_traversal.txt": skill_170,
    "payloads-everything/references/Directory Traversal/Intruder/directory_traversal.txt": skill_171,
    "payloads-everything/references/Directory Traversal/Intruder/dotdotpwn.txt": skill_172,
    "payloads-everything/references/Directory Traversal/Intruder/traversals-8-deep-exotic-encoding.txt": skill_173,
    "payloads-everything/references/Directory Traversal/README.md": skill_174,
    "payloads-everything/references/Encoding Transformations/README.md": skill_175,
    "payloads-everything/references/External Variable Modification/README.md": skill_176,
    "payloads-everything/references/File Inclusion/Intruders/BSD-files.txt": skill_177,
    "payloads-everything/references/File Inclusion/Intruders/JHADDIX_LFI.txt": skill_178,
    "payloads-everything/references/File Inclusion/Intruders/LFI-FD-check.txt": skill_179,
    "payloads-everything/references/File Inclusion/Intruders/LFI-WindowsFileCheck.txt": skill_180,
    "payloads-everything/references/File Inclusion/Intruders/Linux-files.txt": skill_181,
    "payloads-everything/references/File Inclusion/Intruders/List_Of_File_To_Include.txt": skill_182,
    "payloads-everything/references/File Inclusion/Intruders/List_Of_File_To_Include_NullByteAdded.txt": skill_183,
    "payloads-everything/references/File Inclusion/Intruders/Mac-files.txt": skill_184,
    "payloads-everything/references/File Inclusion/Intruders/Traversal.txt": skill_185,
    "payloads-everything/references/File Inclusion/Intruders/Web-files.txt": skill_186,
    "payloads-everything/references/File Inclusion/Intruders/Windows-files.txt": skill_187,
    "payloads-everything/references/File Inclusion/Intruders/dot-slash-PathTraversal_and_LFI_pairing.txt": skill_188,
    "payloads-everything/references/File Inclusion/Intruders/php-filter-iconv.txt": skill_189,
    "payloads-everything/references/File Inclusion/Intruders/simple-check.txt": skill_190,
    "payloads-everything/references/File Inclusion/LFI-to-RCE.md": skill_191,
    "payloads-everything/references/File Inclusion/README.md": skill_192,
    "payloads-everything/references/File Inclusion/Wrappers.md": skill_193,
    "payloads-everything/references/Google Web Toolkit/README.md": skill_194,
    "payloads-everything/references/GraphQL Injection/README.md": skill_195,
    "payloads-everything/references/HTTP Parameter Pollution/README.md": skill_196,
    "payloads-everything/references/Hidden Parameters/README.md": skill_197,
    "payloads-everything/references/Insecure Deserialization/DotNET.md": skill_198,
    "payloads-everything/references/Insecure Deserialization/Files/ruby-serialize.yaml": skill_199,
    "payloads-everything/references/Insecure Deserialization/Java.md": skill_200,
    "payloads-everything/references/Insecure Deserialization/Node.md": skill_201,
    "payloads-everything/references/Insecure Deserialization/PHP.md": skill_202,
    "payloads-everything/references/Insecure Deserialization/Python.md": skill_203,
    "payloads-everything/references/Insecure Deserialization/README.md": skill_204,
    "payloads-everything/references/Insecure Deserialization/Ruby.md": skill_205,
    "payloads-everything/references/Insecure Direct Object References/README.md": skill_206,
    "payloads-everything/references/Insecure Management Interface/Intruder/springboot_actuator.txt": skill_207,
    "payloads-everything/references/Insecure Management Interface/README.md": skill_208,
    "payloads-everything/references/Insecure Randomness/README.md": skill_209,
    "payloads-everything/references/JSON Web Token/README.md": skill_210,
    "payloads-everything/references/Java RMI/README.md": skill_211,
    "payloads-everything/references/LDAP Injection/Intruder/LDAP_FUZZ.txt": skill_212,
    "payloads-everything/references/LDAP Injection/Intruder/LDAP_FUZZ_SMALL.txt": skill_213,
    "payloads-everything/references/LDAP Injection/Intruder/LDAP_attributes.txt": skill_214,
    "payloads-everything/references/LDAP Injection/README.md": skill_215,
    "payloads-everything/references/LaTeX Injection/README.md": skill_216,
    "payloads-everything/references/Mass Assignment/README.md": skill_217,
    "payloads-everything/references/Methodology and Resources/Active Directory Attack.md": skill_218,
    "payloads-everything/references/Methodology and Resources/Bind Shell Cheatsheet.md": skill_219,
    "payloads-everything/references/Methodology and Resources/Cloud - AWS Pentest.md": skill_220,
    "payloads-everything/references/Methodology and Resources/Cloud - Azure Pentest.md": skill_221,
    "payloads-everything/references/Methodology and Resources/Cobalt Strike - Cheatsheet.md": skill_222,
    "payloads-everything/references/Methodology and Resources/Container - Docker Pentest.md": skill_223,
    "payloads-everything/references/Methodology and Resources/Container - Kubernetes Pentest.md": skill_224,
    "payloads-everything/references/Methodology and Resources/Escape Breakout.md": skill_225,
    "payloads-everything/references/Methodology and Resources/HTML Smuggling.md": skill_226,
    "payloads-everything/references/Methodology and Resources/Hash Cracking.md": skill_227,
    "payloads-everything/references/Methodology and Resources/Initial Access.md": skill_228,
    "payloads-everything/references/Methodology and Resources/Linux - Evasion.md": skill_229,
    "payloads-everything/references/Methodology and Resources/Linux - Persistence.md": skill_230,
    "payloads-everything/references/Methodology and Resources/Linux - Privilege Escalation.md": skill_231,
    "payloads-everything/references/Methodology and Resources/MSSQL Server - Cheatsheet.md": skill_232,
    "payloads-everything/references/Methodology and Resources/Metasploit - Cheatsheet.md": skill_233,
    "payloads-everything/references/Methodology and Resources/Methodology and enumeration.md": skill_234,
    "payloads-everything/references/Methodology and Resources/Network Discovery.md": skill_235,
    "payloads-everything/references/Methodology and Resources/Network Pivoting Techniques.md": skill_236,
    "payloads-everything/references/Methodology and Resources/Office - Attacks.md": skill_237,
    "payloads-everything/references/Methodology and Resources/Powershell - Cheatsheet.md": skill_238,
    "payloads-everything/references/Methodology and Resources/Reverse Shell Cheatsheet.md": skill_239,
    "payloads-everything/references/Methodology and Resources/Source Code Management.md": skill_240,
    "payloads-everything/references/Methodology and Resources/Vulnerability Reports.md": skill_241,
    "payloads-everything/references/Methodology and Resources/Web Attack Surface.md": skill_242,
    "payloads-everything/references/Methodology and Resources/Windows - AMSI Bypass.md": skill_243,
    "payloads-everything/references/Methodology and Resources/Windows - DPAPI.md": skill_244,
    "payloads-everything/references/Methodology and Resources/Windows - Defenses.md": skill_245,
    "payloads-everything/references/Methodology and Resources/Windows - Download and Execute.md": skill_246,
    "payloads-everything/references/Methodology and Resources/Windows - Mimikatz.md": skill_247,
    "payloads-everything/references/Methodology and Resources/Windows - Persistence.md": skill_248,
    "payloads-everything/references/Methodology and Resources/Windows - Privilege Escalation.md": skill_249,
    "payloads-everything/references/Methodology and Resources/Windows - Using credentials.md": skill_250,
    "payloads-everything/references/NoSQL Injection/Intruder/MongoDB.txt": skill_251,
    "payloads-everything/references/NoSQL Injection/Intruder/NoSQL.txt": skill_252,
    "payloads-everything/references/NoSQL Injection/README.md": skill_253,
    "payloads-everything/references/OAuth Misconfiguration/README.md": skill_254,
    "payloads-everything/references/ORM Leak/README.md": skill_255,
    "payloads-everything/references/Open Redirect/Intruder/Open-Redirect-payloads.txt": skill_256,
    "payloads-everything/references/Open Redirect/Intruder/open_redirect_wordlist.txt": skill_257,
    "payloads-everything/references/Open Redirect/Intruder/openredirects.txt": skill_258,
    "payloads-everything/references/Open Redirect/README.md": skill_259,
    "payloads-everything/references/Prototype Pollution/README.md": skill_260,
    "payloads-everything/references/Race Condition/README.md": skill_261,
    "payloads-everything/references/Regular Expression/README.md": skill_262,
    "payloads-everything/references/Request Smuggling/README.md": skill_263,
    "payloads-everything/references/Reverse Proxy Misconfigurations/README.md": skill_264,
    "payloads-everything/references/SAML Injection/README.md": skill_265,
    "payloads-everything/references/SQL Injection/BigQuery Injection.md": skill_266,
    "payloads-everything/references/SQL Injection/Cassandra Injection.md": skill_267,
    "payloads-everything/references/SQL Injection/DB2 Injection.md": skill_268,
    "payloads-everything/references/SQL Injection/Intruder/Auth_Bypass.txt": skill_269,
    "payloads-everything/references/SQL Injection/Intruder/Auth_Bypass2.txt": skill_270,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_MSSQL-WHERE_Time.txt": skill_271,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_MSSQL.txt": skill_272,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_MSSQL_Enumeration.txt": skill_273,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_MYSQL.txt": skill_274,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_MySQL-WHERE_Time.txt": skill_275,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_MySQL_ReadLocalFiles.txt": skill_276,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_Oracle.txt": skill_277,
    "payloads-everything/references/SQL Injection/Intruder/FUZZDB_Postgres_Enumeration.txt": skill_278,
    "payloads-everything/references/SQL Injection/Intruder/Generic_ErrorBased.txt": skill_279,
    "payloads-everything/references/SQL Injection/Intruder/Generic_Fuzz.txt": skill_280,
    "payloads-everything/references/SQL Injection/Intruder/Generic_TimeBased.txt": skill_281,
    "payloads-everything/references/SQL Injection/Intruder/Generic_UnionSelect.txt": skill_282,
    "payloads-everything/references/SQL Injection/Intruder/SQLi_Polyglots.txt": skill_283,
    "payloads-everything/references/SQL Injection/MSSQL Injection.md": skill_284,
    "payloads-everything/references/SQL Injection/MySQL Injection.md": skill_285,
    "payloads-everything/references/SQL Injection/OracleSQL Injection.md": skill_286,
    "payloads-everything/references/SQL Injection/PostgreSQL Injection.md": skill_287,
    "payloads-everything/references/SQL Injection/README.md": skill_288,
    "payloads-everything/references/SQL Injection/SQLite Injection.md": skill_289,
    "payloads-everything/references/SQL Injection/SQLmap.md": skill_290,
    "payloads-everything/references/Server Side Include Injection/Files/ssi_esi.txt": skill_291,
    "payloads-everything/references/Server Side Include Injection/README.md": skill_292,
    "payloads-everything/references/Server Side Request Forgery/README.md": skill_293,
    "payloads-everything/references/Server Side Request Forgery/SSRF-Advanced-Exploitation.md": skill_294,
    "payloads-everything/references/Server Side Request Forgery/SSRF-Cloud-Instances.md": skill_295,
    "payloads-everything/references/Server Side Template Injection/ASP.md": skill_296,
    "payloads-everything/references/Server Side Template Injection/Elixir.md": skill_297,
    "payloads-everything/references/Server Side Template Injection/Java.md": skill_298,
    "payloads-everything/references/Server Side Template Injection/JavaScript.md": skill_299,
    "payloads-everything/references/Server Side Template Injection/PHP.md": skill_300,
    "payloads-everything/references/Server Side Template Injection/Python.md": skill_301,
    "payloads-everything/references/Server Side Template Injection/README.md": skill_302,
    "payloads-everything/references/Server Side Template Injection/Ruby.md": skill_303,
    "payloads-everything/references/Tabnabbing/README.md": skill_304,
    "payloads-everything/references/Type Juggling/README.md": skill_305,
    "payloads-everything/references/Upload Insecure Files/CVE ZIP Symbolic Link/generate.sh": skill_306,
    "payloads-everything/references/Upload Insecure Files/Configuration Apache .htaccess/README.md": skill_307,
    "payloads-everything/references/Upload Insecure Files/EICAR/eicar.txt": skill_308,
    "payloads-everything/references/Upload Insecure Files/README.md": skill_309,
    "payloads-everything/references/Virtual Hosts/README.md": skill_310,
    "payloads-everything/references/Web Cache Deception/Intruders/param_miner_lowercase_headers.txt": skill_311,
    "payloads-everything/references/Web Cache Deception/README.md": skill_312,
    "payloads-everything/references/Web Sockets/README.md": skill_313,
    "payloads-everything/references/XPATH Injection/README.md": skill_314,
    "payloads-everything/references/XS-Leak/README.md": skill_315,
    "payloads-everything/references/XSLT Injection/README.md": skill_316,
    "payloads-everything/references/XSS Injection/1 - XSS Filter Bypass.md": skill_317,
    "payloads-everything/references/XSS Injection/2 - XSS Polyglot.md": skill_318,
    "payloads-everything/references/XSS Injection/3 - XSS Common WAF Bypass.md": skill_319,
    "payloads-everything/references/XSS Injection/4 - CSP Bypass.md": skill_320,
    "payloads-everything/references/XSS Injection/5 - XSS in Angular.md": skill_321,
    "payloads-everything/references/XSS Injection/Intruders/0xcela_event_handlers.txt": skill_322,
    "payloads-everything/references/XSS Injection/Intruders/BRUTELOGIC-XSS-JS.txt": skill_323,
    "payloads-everything/references/XSS Injection/Intruders/BRUTELOGIC-XSS-STRINGS.txt": skill_324,
    "payloads-everything/references/XSS Injection/Intruders/IntrudersXSS.txt": skill_325,
    "payloads-everything/references/XSS Injection/Intruders/JHADDIX_XSS.txt": skill_326,
    "payloads-everything/references/XSS Injection/Intruders/MarioXSSVectors.txt": skill_327,
    "payloads-everything/references/XSS Injection/Intruders/RSNAKE_XSS.txt": skill_328,
    "payloads-everything/references/XSS Injection/Intruders/XSSDetection.txt": skill_329,
    "payloads-everything/references/XSS Injection/Intruders/XSS_Polyglots.txt": skill_330,
    "payloads-everything/references/XSS Injection/Intruders/jsonp_endpoint.txt": skill_331,
    "payloads-everything/references/XSS Injection/Intruders/port_swigger_xss_cheatsheet_event_handlers.txt": skill_332,
    "payloads-everything/references/XSS Injection/Intruders/xss_alert.txt": skill_333,
    "payloads-everything/references/XSS Injection/Intruders/xss_alert_identifiable.txt": skill_334,
    "payloads-everything/references/XSS Injection/Intruders/xss_payloads_quick.txt": skill_335,
    "payloads-everything/references/XSS Injection/Intruders/xss_swf_fuzz.txt": skill_336,
    "payloads-everything/references/XSS Injection/README.md": skill_337,
    "payloads-everything/references/XXE Injection/Intruders/XXE_Fuzzing.txt": skill_338,
    "payloads-everything/references/XXE Injection/Intruders/xml-attacks.txt": skill_339,
    "payloads-everything/references/XXE Injection/README.md": skill_340,
    "payloads-everything/references/Zip Slip/README.md": skill_341,
    "pentest-fuzz-skill/README.md": skill_342,
    "pentest-fuzz-skill/SKILL.md": skill_343,
    "pentest-fuzz-skill/deserialization/README.md": skill_344,
    "pentest-fuzz-skill/deserialization/fuzz.txt": skill_345,
    "pentest-fuzz-skill/deserialization/fuzzing.md": skill_346,
    "pentest-fuzz-skill/deserialization/overview.md": skill_347,
    "pentest-fuzz-skill/evals/evals.json": skill_348,
    "pentest-fuzz-skill/idor/README.md": skill_349,
    "pentest-fuzz-skill/idor/fuzz.txt": skill_350,
    "pentest-fuzz-skill/idor/fuzzing.md": skill_351,
    "pentest-fuzz-skill/idor/overview.md": skill_352,
    "pentest-fuzz-skill/jwt/README.md": skill_353,
    "pentest-fuzz-skill/jwt/fuzz.txt": skill_354,
    "pentest-fuzz-skill/jwt/fuzzing.md": skill_355,
    "pentest-fuzz-skill/jwt/overview.md": skill_356,
    "pentest-fuzz-skill/lfi-rfi/README.md": skill_357,
    "pentest-fuzz-skill/lfi-rfi/fuzz.txt": skill_358,
    "pentest-fuzz-skill/lfi-rfi/fuzzing.md": skill_359,
    "pentest-fuzz-skill/lfi-rfi/overview.md": skill_360,
    "pentest-fuzz-skill/rce/README.md": skill_361,
    "pentest-fuzz-skill/rce/fuzz.txt": skill_362,
    "pentest-fuzz-skill/rce/fuzzing.md": skill_363,
    "pentest-fuzz-skill/rce/overview.md": skill_364,
    "pentest-fuzz-skill/sqli/README.md": skill_365,
    "pentest-fuzz-skill/sqli/fuzz.txt": skill_366,
    "pentest-fuzz-skill/sqli/fuzzing.md": skill_367,
    "pentest-fuzz-skill/sqli/overview.md": skill_368,
    "pentest-fuzz-skill/ssrf/README.md": skill_369,
    "pentest-fuzz-skill/ssrf/fuzz.txt": skill_370,
    "pentest-fuzz-skill/ssrf/fuzzing.md": skill_371,
    "pentest-fuzz-skill/ssrf/overview.md": skill_372,
    "pentest-fuzz-skill/ssti/README.md": skill_373,
    "pentest-fuzz-skill/ssti/fuzz.txt": skill_374,
    "pentest-fuzz-skill/ssti/fuzzing.md": skill_375,
    "pentest-fuzz-skill/ssti/overview.md": skill_376,
    "pentest-fuzz-skill/xss/README.md": skill_377,
    "pentest-fuzz-skill/xss/fuzz.txt": skill_378,
    "pentest-fuzz-skill/xss/fuzzing.md": skill_379,
    "pentest-fuzz-skill/xss/overview.md": skill_380,
    "pentest-fuzz-skill/xxe/README.md": skill_381,
    "pentest-fuzz-skill/xxe/fuzz.txt": skill_382,
    "pentest-fuzz-skill/xxe/fuzzing.md": skill_383,
    "pentest-fuzz-skill/xxe/overview.md": skill_384,
    "pentest/SKILL.md": skill_385,
    "pentest/references/automation.md": skill_386,
    "pentest/references/binary-audit.md": skill_387,
    "pentest/references/custom-rules.md": skill_388,
    "pentest/references/disclosure.md": skill_389,
    "pentest/references/external-platforms.md": skill_390,
    "pentest/references/fuzzing.md": skill_391,
    "pentest/references/hack-skills.md": skill_392,
    "pentest/references/mobile-pentest.md": skill_393,
    "pentest/references/pentest-self-audit.md": skill_394,
    "pentest/references/source-audit.md": skill_395,
    "pentest/references/target-selection.md": skill_396,
    "recon/SKILL.md": skill_397,
    "recon/references/vuln-class-matrix.md": skill_398,
    "remote-cmd-execution/SKILL.md": skill_399,
    "targeted-pentest/SKILL.md": skill_400,
    "targeted-pentest/references/auth-and-access.md": skill_401,
    "targeted-pentest/references/auth-infra.md": skill_402,
    "targeted-pentest/references/auth-jwt.md": skill_403,
    "targeted-pentest/references/client-side-advanced.md": skill_404,
    "targeted-pentest/references/client-side.md": skill_405,
    "targeted-pentest/references/cves.md": skill_406,
    "targeted-pentest/references/field-notes.md": skill_407,
    "targeted-pentest/references/node-and-prototype.md": skill_408,
    "targeted-pentest/references/server-side-advanced-2.md": skill_409,
    "targeted-pentest/references/server-side-advanced.md": skill_410,
    "targeted-pentest/references/server-side-deser.md": skill_411,
    "targeted-pentest/references/server-side-exec-2.md": skill_412,
    "targeted-pentest/references/server-side-exec.md": skill_413,
    "targeted-pentest/references/server-side.md": skill_414,
    "targeted-pentest/references/sql-injection.md": skill_415,
} as const

export const RUNTIME_ASSET_FILES = {
    "Dockerfile": runtime_0,
    "provision-pentest-vps.sh": runtime_1,
} as const
