import type { CustomProvider } from "./types"

const ZAI_COMPAT = {
    supportsDeveloperRole: false,
    thinkingFormat: "zai",
} as const

const zhipuai: CustomProvider = {
    name: "zhipuai",
    config: {
        baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
        apiKey: "ZHIPU_API_KEY",
        api: "openai-completions",
        models: [
            {
                id: "glm-4.5",
                name: "GLM-4.5",
                reasoning: true,
                input: ["text"],
                cost: { input: 0.6, output: 2.2, cacheRead: 0.11, cacheWrite: 0 },
                contextWindow: 131072,
                maxTokens: 98304,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.5-air",
                name: "GLM-4.5-Air",
                reasoning: true,
                input: ["text"],
                cost: { input: 0.2, output: 1.1, cacheRead: 0.03, cacheWrite: 0 },
                contextWindow: 131072,
                maxTokens: 98304,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.5-flash",
                name: "GLM-4.5-Flash",
                reasoning: true,
                input: ["text"],
                cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
                contextWindow: 131072,
                maxTokens: 98304,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.5v",
                name: "GLM-4.5V",
                reasoning: true,
                input: ["text", "image"],
                cost: { input: 0.6, output: 1.8, cacheRead: 0, cacheWrite: 0 },
                contextWindow: 64000,
                maxTokens: 16384,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.6",
                name: "GLM-4.6",
                reasoning: true,
                input: ["text"],
                cost: { input: 0.6, output: 2.2, cacheRead: 0.11, cacheWrite: 0 },
                contextWindow: 204800,
                maxTokens: 131072,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.6v",
                name: "GLM-4.6V",
                reasoning: true,
                input: ["text", "image"],
                cost: { input: 0.3, output: 0.9, cacheRead: 0, cacheWrite: 0 },
                contextWindow: 128000,
                maxTokens: 32768,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.7",
                name: "GLM-4.7",
                reasoning: true,
                input: ["text"],
                cost: { input: 0.6, output: 2.2, cacheRead: 0.11, cacheWrite: 0 },
                contextWindow: 204800,
                maxTokens: 131072,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-4.7-flash",
                name: "GLM-4.7-Flash",
                reasoning: true,
                input: ["text"],
                cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
                contextWindow: 200000,
                maxTokens: 131072,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-5-turbo",
                name: "GLM-5-Turbo",
                reasoning: true,
                input: ["text"],
                cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 },
                contextWindow: 204800,
                maxTokens: 131072,
                compat: ZAI_COMPAT,
            },
            {
                id: "glm-5.1",
                name: "GLM-5.1",
                reasoning: true,
                input: ["text"],
                cost: { input: 1.2, output: 4, cacheRead: 0.24, cacheWrite: 0 },
                contextWindow: 204800,
                maxTokens: 131072,
                compat: ZAI_COMPAT,
            },
        ],
    },
}

export default zhipuai
