import { readdirSync, statSync } from "fs"
import { mkdir } from "fs/promises"
import { basename, dirname, extname, relative, resolve } from "path"

const projectRoot = resolve(import.meta.dir, "..")
const configDir = resolve(projectRoot, "packages/core/src/config")
const promptsBuiltinDir = resolve(configDir, "prompts/builtin")
const skillsBuiltinDir = resolve(configDir, "skills/builtin")
const mcpDir = resolve(projectRoot, "mcp")
const mcpBuiltinDir = resolve(configDir, "mcp/builtin")
const runtimeDir = resolve(projectRoot, "packages/core/src/runtime")
const runtimeAssetsDir = resolve(runtimeDir, "assets")
const outputPath = resolve(configDir, "builtin-assets.generated.ts")

function collectFiles(dir: string): string[] {
    const files: string[] = []

    function walk(currentDir: string) {
        for (const entry of readdirSync(currentDir)) {
            if (entry.startsWith(".")) continue
            const fullPath = resolve(currentDir, entry)
            const stat = statSync(fullPath)
            if (stat.isDirectory()) {
                walk(fullPath)
            } else {
                files.push(relative(configDir, fullPath).replaceAll("\\", "/"))
            }
        }
    }

    walk(dir)
    return files.sort()
}

function escapeIdentifier(value: string): string {
    return value.replace(/[^a-zA-Z0-9_]/g, "_")
}

function shouldIncludeBuiltinSkillFile(file: string): boolean {
    const ext = extname(file).toLowerCase()
    if (ext === ".md" || ext === ".txt" || ext === ".json" || ext === ".sh" || ext === ".yaml" || ext === ".yml") return true
    if (!ext && file.includes("/scripts/")) return true
    return basename(file) === "SKILL"
}

export async function generateBuiltinAssets(): Promise<void> {
    const promptFiles = collectFiles(promptsBuiltinDir).filter((file) => file.endsWith(".md"))
    const skillFiles = collectFiles(skillsBuiltinDir).filter(shouldIncludeBuiltinSkillFile)
    await mkdir(mcpBuiltinDir, { recursive: true })
    const mcpFiles: string[] = []
    for (const entry of readdirSync(mcpDir)) {
        if (!entry.endsWith(".py")) continue
        const sourcePath = resolve(mcpDir, entry)
        const destPath = resolve(mcpBuiltinDir, entry)
        await Bun.write(destPath, Bun.file(sourcePath))
        mcpFiles.push(`mcp/builtin/${entry}`)
    }
    mcpFiles.sort()
    const runtimeFiles = collectFiles(runtimeAssetsDir)

    const lines: string[] = ["// generated by scripts/generate-builtin-assets.ts"]

    for (const [index, file] of promptFiles.entries()) {
        lines.push(`import prompt_${escapeIdentifier(String(index))} from "./${file}" with { type: "file" }`)
    }

    for (const [index, file] of skillFiles.entries()) {
        lines.push(`import skill_${escapeIdentifier(String(index))} from "./${file}" with { type: "file" }`)
    }

    for (const [index, file] of mcpFiles.entries()) {
        lines.push(`import mcp_${escapeIdentifier(String(index))} from "./${file}" with { type: "file" }`)
    }

    for (const [index, file] of runtimeFiles.entries()) {
        lines.push(`import runtime_${escapeIdentifier(String(index))} from "${file}" with { type: "file" }`)
    }

    lines.push("")
    lines.push("export const BUILTIN_PROMPTS = {")
    for (const [index, file] of promptFiles.entries()) {
        lines.push(`    ${JSON.stringify(file.slice("prompts/builtin/".length))}: prompt_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")
    lines.push("export const BUILTIN_SKILL_FILES = {")
    for (const [index, file] of skillFiles.entries()) {
        lines.push(`    ${JSON.stringify(file.slice("skills/builtin/".length))}: skill_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")
    lines.push("export const BUILTIN_MCP_FILES = {")
    for (const [index, file] of mcpFiles.entries()) {
        lines.push(`    ${JSON.stringify(basename(file))}: mcp_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")
    lines.push("export const RUNTIME_ASSET_FILES = {")
    for (const [index, file] of runtimeFiles.entries()) {
        lines.push(`    ${JSON.stringify(file.slice("../runtime/assets/".length))}: runtime_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")

    await Bun.write(outputPath, lines.join("\n"))
}

if (import.meta.path === Bun.main) {
    await generateBuiltinAssets()
}
